"""Dropped table Task

Revision ID: 09113f2f4f3b
Revises: ecdca31e0968
Create Date: 2022-09-14 14:33:57.054968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09113f2f4f3b'
down_revision = 'ecdca31e0968'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
