"""Dropped table Task

Revision ID: ecdca31e0968
Revises: 77f3305b54f5
Create Date: 2022-09-14 14:21:44.959524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecdca31e0968'
down_revision = '77f3305b54f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_id', table_name='task')
    op.drop_index('ix_task_text', table_name='task')
    op.drop_table('task')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('text', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_task_text', 'task', ['text'], unique=False)
    op.create_index('ix_task_id', 'task', ['id'], unique=False)
    # ### end Alembic commands ###
